post_install() {
    systemctl enable libvirtd org.cups.cupsd
    sed -i 's/basic/desktop/g' /etc/docker-btrfs.json
    cp /opt/chendsystem/etc/libvirt/qemu.conf /etc/libvirt/qemu.conf
    ln -s /opt/cuda /usr/local/cuda

    # eaf dependencies
    mkdir /opt/chendsystem/app
    cd /opt/chendsystem/app
    git clone --depth=1 -b master https://github.com/emacs-eaf/emacs-application-framework.git
    sh /opt/chendsystem/app/install-eaf.sh
}

